### ISSUE TITLE
HFLA ISSUE: Refactor "Issue Trigger" workflow to use existing team function

### ISSUE THREAD

**Issue by t-will-gillis** [t-will-gillis/website#1146]
### Overview
In the "Issue Trigger" workflow, we want to refactor the team membership check to use an existing Website function instead of relying on an outside module.

### Action Items
Refer to the `issue-trigger.yml`[^1] workflow file and find the workflow step beginning with the comment:
  `# Checks if user is on the 'website-write' team`
- [ ] Replace:
  ```  
      # Checks if user is on the 'website-write' team
      - uses: tspascoal/get-user-teams-membership@v3
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          organization: 'hackforla'
          team: 'website-write'
          GITHUB_TOKEN: ${{ secrets.TEAMS }}  
  ```  
  with:  
  ```  
      # Checks if user is on the 'website-write' team
      - name: Check Team Membership
        id: check-team-membership
        uses: actions/github-script@v7
        with:
          script: |
            const username = '${{ github.actor }}'
            const team = 'website-write'
            const script = require('./github-actions/utils/check-team-membership.js')
            return script(github, username, team)          
  ```  
- [ ] Replace:
  ```  
       # Posts comment only if user is team member (based on the previous action's result)
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
  ```  
  with:  
  ```  
      # Posts comment only if user is team member (based on the previous action's result)
      - if: ${{ steps.checkUserMember.outputs.check-team-membership == 'true' }}
  ``` 

- [ ] Test in your own repo to demonstrate that the refactored script is functioning as intended.

Merge team: After this issue is reviewed, approved, and merged:
- [ ] Remove the `TEAMS` secret from the Admin account, and 
- [ ] Remove the `TEAMS` token from the HackforLA-bot account. 

### Resources/Instructions
[^1]: [Issue Trigger Workflow](https://github.com/t-will-gillis/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
